openapi: 3.0.1
info:
  title: TryDome API
  description: API for TryDome template discovery and installation.
  version: '1.0'
servers:
  - url: https://api.staging.trydome.io/api/v1
    description: Staging server
paths:
  /templates/discovery/install:
    post:
      summary: Install a template discovery
      description: Endpoint to install a template discovery.
      operationId: installTemplateDiscovery
      tags:
        - Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                organization:
                  type: string
                  example: ""
                destination:
                  type: string
                  example: "Jasmine Blog"
                isPrivate:
                  type: boolean
                  example: true
                discovery:
                  $ref: "#/components/schemas/Discovery"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Template installed successfully"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - jwt: []
      x-codegen-request-body-name: body

  /templates/discovery/deploy:
    post:
      summary: Deploy a template discovery
      description: Endpoint to deploy a template discovery.
      operationId: deployTemplateDiscovery
      tags:
        - Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId:
                  type: string
                  example: "5918273"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Template deployed successfully"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - jwt: []
      x-codegen-request-body-name: body

  /templates/discovery/title:
    post:
      summary: Generate title for a template discovery
      description: Endpoint to generate title for a template discovery.
      operationId: setTitleTemplateDiscovery
      tags:
        - Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productIdea:
                  type: string
                  example: "I want to build a personal blog"
                productName:
                  type: string
                  example: ""
                industry:
                  type: string
                  example: "personal blog"
                brandVoice:
                  type: string
                  example: "share!"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Title set successfully"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - jwt: []
      x-codegen-request-body-name: body

  /templates/discovery/color:
    post:
      summary: Generate color for a template discovery
      description: Endpoint to generate color for a template discovery.
      operationId: setColorTemplateDiscovery
      tags:
        - Templates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productIdea:
                  type: string
                  example: "I want to build a personal blog"
                productName:
                  type: string
                  example: ""
                industry:
                  type: string
                  example: "personal blog"
                brandVoice:
                  type: string
                  example: "share!"
                colorDescription:
                  type: string
                  example: "warm"
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Color set successfully"
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '500':
          description: Internal server error
      security:
        - jwt: []
      x-codegen-request-body-name: body
  /api/v1/templates/discovery/download:
    post:
      summary: Download Discovery Template
      tags:
        - Templates
      description: Downloads a discovery template based on the provided settings.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DiscoveryRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
        '400':
          description: Bad request
        '500':
          description: Internal server error
components:
  schemas:
    DiscoveryRequest:
      type: object
      properties:
        organization:
          type: string
        destination:
          type: string
        isPrivate:
          type: boolean
        discovery:
          $ref: '#/components/schemas/Discovery'
    Discovery:
      type: object
      properties:
        idea:
          type: object
          properties:
            productIdea:
              type: string
            productName:
              type: string
            industry:
              type: string
            brandVoice:
              type: string
            colorDescription:
              type: string
            painPoint:
              type: string
            outcome:
              type: string
        settings:
          type: object
          properties:
            auth:
              type: object
              properties:
                isSelected:
                  type: boolean
                solution:
                  type: string
            database:
              type: object
              properties:
                isSelected:
                  type: boolean
                type:
                  type: string
            payment:
              type: object
              properties:
                isSelected:
                  type: boolean
                solution:
                  type: string
                plan:
                  type: string
            selectedTitle:
              type: object
              properties:
                title:
                  type: string
                subtitle:
                  type: string
            components:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: BannerWithButton
